version: '3'

services:
  php:
    build: ./images/php
    volumes: 
      - ./:/var/www/html
    ports: 
      - '8080:80'
    links:
      - mysql
      - redis
  python:
    build: ./images/python
    volumes:
      - .:/app
    links:
     - mysql
     - redis
  mysql:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    ports: 
      - '3300:3306'
    environment:
      MYSQL_DATABASE: gma
      MYSQL_ROOT_PASSWORD: test
  redis:
    image: redis:3.2
    ports: 
      - '6300:6379'
